#!/usr/bin/env python 
"""The script to build my resumes."""

env = Environment(tools=["pandoc"])
env.Pandoc("full.html", "full.text",
           PANDOCFLAGS="--self-contained --css=style.css")
env.Pandoc("short.html", "short.text",
           PANDOCFLAGS="--self-contained --css=short.css")

