#!/usr/bin/env python

import os

Import("env prefix")

prefix = os.path.join(prefix, Dir(os.curdir).name)
for src in ("index.md",
            ):
    root, _ = os.path.splitext(src)
    env.Pandoc(os.path.join(prefix, root + ".html"), src)

for src in ("druid.html",
            "ranger.html",
            "spells.css"):
    env.Install(prefix, src)

