#!/usr/bin/env python


icons = [File(i) for i in ("email.svg",
                           "github.svg",
                           "linkedin.svg",
                           "rss.svg",
                           "stackoverflow.svg")]
Return("icons")
