#!/usr/bin/env python

import os

Import("env")

prefix = os.path.join(env["prefix"], Dir(os.curdir).name)
for src in ("index.markdown",
            ):
    root, _ = os.path.splitext(src)
    env.Pandoc(os.path.join(prefix, root + ".html"), src)

Export("env prefix")
for subdir in ("spell_lists",
               "dnd",
               ):
    SConscript(os.path.join(subdir, "SConscript"))

